### ISSUE TITLE
Bug with Better Water Management

### ISSUE THREAD

**Issue by Remodor** [ds5678/mod_list#1]
Hello ds!
I know writing an issue here for a different mod is really bad practice. Big apologies but I couldn't find any better solution to write you. 
Please allow issues on your forked mods:
It is in the forked repo settings under options/features.
![image](https://user-images.githubusercontent.com/57945765/109320925-e040ec00-7850-11eb-9418-6528ba1119dc.png)

The bug:
When you boil water on a fire/stove and you select the drink option, you won't drink and after picking up the water the container (tin can/ pot) disappears from your inventory. Drinking straight away may seems not necessary but if you start without a bottle there is no method to drink anything, as you can't take the water..

I tested this in story mode and in challenge mode and only with better water management enabled.

As I am also a modder (although not for tld till now) and have quite some knowledge with unity, harmony and even some Transpiler, I can also try helping you to fix this bug if you are interested.

Best Regards

**Comment by Remodor** [comment]
Haha, I just saw this:
![image](https://user-images.githubusercontent.com/57945765/109324810-7840d480-7855-11eb-875c-c499269ca1c8.png)

Is this maybe the problem? should I fix this for you :D

I will have a look, maybe I can solve this!

**Comment by ds5678** [comment]
Are you a part of the discord server? It would have been better to message
me there.

**Comment by ds5678** [comment]
https://discord.gg/vEapvS9n
